# Generated by Django 5.2.6 on 2025-09-17 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='is_served',
            new_name='is_delivered',
        ),
    ]
