# Generated by Django 5.2.6 on 2025-09-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_is_served_orderitem_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='kitchen_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready')], default='pending', max_length=15),
        ),
    ]
