# Generated by Django 5.2.6 on 2025-09-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_menuitem_category_menuitem_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
