# Generated by Django 5.2.6 on 2025-09-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_staff_options_alter_staff_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Veg', 'Vegetarian'), ('Non-Veg', 'Non-Vegetarian')], default='Veg', max_length=100),
        ),
    ]
