# Generated by Django 5.2.6 on 2025-09-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_menuitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgst', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sgst', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
