# Generated by Django 5.2.6 on 2025-09-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_taxsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='meal_type',
            field=models.CharField(choices=[('burgers & pizzas', 'Burgers & Pizzas'), ('salads', 'Salads'), ('breakfast', 'Breakfast'), ('starter', 'Starter'), ('soup', 'Soup'), ('main_course', 'Main Course'), ('rice', 'Rice'), ('noodles', 'Noodles'), ('dessert', 'Dessert'), ('cocktails', 'Cocktails'), ('beverage', 'Beverage')], default='main_course', max_length=50),
        ),
    ]
