# Generated by Django 5.2.6 on 2025-10-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_menuitem_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='meal_type',
            field=models.CharField(choices=[('burgers', 'Burgers'), ('pizzas', 'Pizzas'), ('salads', 'Salads'), ('breakfast', 'Breakfast'), ('starter', 'Starter'), ('soup', 'Soup'), ('main_course', 'Main Course'), ('rice', 'Rice'), ('noodles', 'Noodles'), ('dessert', 'Dessert'), ('juices', 'Juices'), ('beverage', 'Beverage')], default='main_course', max_length=50),
        ),
    ]
