# Generated by Django 5.2.6 on 2025-10-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_bill_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='customer',
        ),
    ]
